import { memoize } from "../lib/functional.ts";
import { pipe } from "../lib/pipe.ts";
import { getLines, pop$, then } from "../lib/streams.ts";

const fish = await pipe(
  getLines("06.input.txt"),
  pop$,
  then((x) => x!.split(",").map(Number)),
);

const populationAt = memoize((days: number): number => {
  if (days <= 0) return 1;
  return populationAt(days - 7) + populationAt(days - 9);
});

function evolve(fish: number[], days: number) {
  // add up all the populations generated by each fish,
  // normalizing their current reproductive cycle by subtracting from days
  return fish.reduce((s, f) => s + populationAt(days - f), 0);
}

console.log("Part 1:", evolve(fish, 80));
console.log("Part 2:", evolve(fish, 256));
